"""create airport transfer rules

Revision ID: fafb51b829f9
Revises: 
Create Date: 2026-07-22 12:23:38.908156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafb51b829f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport_transfer_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('airport_code', sa.String(length=3), nullable=False),
    sa.Column('arrival_terminal', sa.String(length=10), nullable=True),
    sa.Column('departure_terminal', sa.String(length=10), nullable=True),
    sa.Column('terminal_transfer_minutes', sa.Integer(), nullable=False),
    sa.Column('security_minutes', sa.Integer(), nullable=False),
    sa.Column('immigration_minutes', sa.Integer(), nullable=False),
    sa.Column('baggage_recheck_minutes', sa.Integer(), nullable=False),
    sa.Column('self_transfer', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_code', 'arrival_terminal', 'departure_terminal', 'self_transfer', name='uq_airport_transfer_rule')
    )
    op.create_index(op.f('ix_airport_transfer_rules_airport_code'), 'airport_transfer_rules', ['airport_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airport_transfer_rules_airport_code'), table_name='airport_transfer_rules')
    op.drop_table('airport_transfer_rules')
    # ### end Alembic commands ###
